const test=require('node:test'),assert=require('node:assert/strict'),C=require('./daily_work_core'),P=require('./daily_sale_plan');
const item={code:'TEST_01',shopItemId:'testId',stock:1};
const spec={id:'one',url:'https://jp.mercari.com/item/m12345',code:item.code,productId:item.shopItemId,title:'テスト商品',platform:'mercari',kind:'sale',normalPrice:10000,price:9000,startAt:'2026-10-01T20:00:00+09:00',endAt:'2026-10-01T23:00:00+09:00'};
const file=j=>({format:'daily-staff-v1',batch:'test',createdAt:'2026-09-30',jobs:[j]});
const now=Date.parse('2026-10-01T21:00:00+09:00');
function ready(){let s=P.prepare(C.merge({jobs:[]},file(spec)),now);s=P.screen(s,'one',{currentPrice:10000,likes:null},now);return P.pause(s,'mercari',spec.endAt,now);}
test('開始前・期限切れ・商品違い・在庫ゼロを完了にしない',()=>{const s=C.merge({jobs:[]},file(spec));for(const [items,t]of [[[item],now-7200000],[[item],now+7200000],[[{...item,shopItemId:'other'}],now],[[{...item,stock:0}],now]])assert.throws(()=>C.transition(s,'one','done',items,t));assert.equal(s.jobs[0].status,'pending');});
test('終了処理には実際に保存した販路の元価格を使う・再取り込みで進捗保持',()=>{let s=ready();s=C.transition(s,'one','done',[item],now);assert.equal(s.jobs[1].spec.price,10000);assert.equal(s.jobs[1].spec.notBefore,spec.endAt);s=C.merge(s,file(spec));assert.equal(s.jobs.length,2);assert.equal(s.jobs[0].status,'done');assert.throws(()=>C.merge(s,file({...spec,price:8800})));});
test('完了取り消し・終了処理後の巻戻しを防止',()=>{let s=C.transition(ready(),'one','done',[item],now);assert.throws(()=>C.transition(s,'one','pending',[item],now));assert.equal(s.jobs.length,2);s=C.transition(s,'one:restore','done',[item],now+10800000);assert.throws(()=>C.transition(s,'one','pending',[item],now+10800000));});
test('売却記録は当該販路の復元作業を停止する',()=>{let s=C.transition(ready(),'one','done',[item],now);s=C.transition(s,'one','sold',[item],now);assert.equal(s.jobs[1].status,'sold');});
test('原価入り指示・Shops・不正金額・重複指示は拒否',()=>{for(const j of [{...spec,cost:3},{...spec,platform:'shops'},{...spec,price:0},{...spec,endAt:'2026-10-01'}])assert.throws(()=>C.merge({jobs:[]},file(j)));assert.throws(()=>C.validate({...file(spec),jobs:[spec,spec]}));});
test('同額記録と例外は価格変更の完了に混同しない',()=>{const s=C.merge({jobs:[]},file({...spec,kind:'price'}));assert.equal(C.transition(s,'one','unchanged',[item],now).jobs[0].status,'unchanged');assert.equal(C.transition(s,'one','missing',[],now).jobs[0].status,'missing');assert.throws(()=>C.transition(C.merge({jobs:[]},file(spec)),'one','unchanged',[item],now));});
test('オーナー保留は時刻到来で自動解除しない',()=>assert.match(C.blocked({...spec,holdReason:'仕様不一致'},[item],now),/仕様/));
test('保存結果を復元できる・新しい記録を古いバックアップで上書きしない',()=>{const s=C.transition(ready(),'one','done',[item],now);const backup={format:'daily-staff-results-v1',exportedAt:new Date(now).toISOString(),jobs:s.jobs,saleRounds:s.saleRounds,salePauses:s.salePauses};assert.deepEqual(C.restore({jobs:[]},backup),s);assert.deepEqual(C.restore(s,backup),s);const pending=C.merge({jobs:[]},file(spec));assert.throws(()=>C.restore(pending,backup));assert.equal(pending.jobs[0].status,'pending');assert.throws(()=>C.restore({jobs:[]},{...backup,cost:10}));});
