(function(){'use strict';
const C=window.DailyWorkCore,P=window.DailySalePlan,KEY=window.DAILY_WORK_STORAGE_KEY||'daily_staff_work_v1',names={mercari:'メルカリ',rakuma:'ラクマ',yahoo_flea:'Yahoo!フリマ'},labels={pending:'未着手',done:'完了',unchanged:'指定価格どおり（変更なし）',missing:'見つからない',sold:'この販路で売却済み',on_sale:'別のセール中',mismatch:'商品違い',lower:'指定より安い',hold:'オーナーへ相談'};
let panel,selected,tab='today',message='',loadError=false;
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{"jobs":[]}');if(!Array.isArray(x.jobs))throw Error();return x;}catch(e){loadError=true;return {jobs:[]};}}
let state=read(),lastSaved=localStorage.getItem(KEY);
function save(next){if(loadError)throw Error('作業データを読めません。上書きせずオーナーへ連絡してください');if(localStorage.getItem(KEY)!==lastSaved){state=read();lastSaved=localStorage.getItem(KEY);throw Error('別の画面で記録が更新されました。再表示してから操作してください');}const raw=JSON.stringify(next);localStorage.setItem(KEY,raw);lastSaved=raw;state=next;}
function el(tag,text,parent,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;if(parent)parent.appendChild(n);return n;}
function button(text,fn,parent){const b=el('button',text,parent);b.onclick=async()=>{try{await fn();}catch(e){message=e.message;render();}};return b;}
function link(text,url,parent){if(window.DAILY_WORK_PREVIEW)return el('span',text+'（見本）',parent);const a=el('a',text,parent);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function money(n){return Number(n).toLocaleString()+'円';}
function stock(){return window.items||[];}
function copy(t){return navigator.clipboard.writeText(t).then(()=>{message='コピーしました';render();});}
function download(name,obj){const u=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function report(r){const j=r.spec;return `管理番号：${j.code}\n商品名：${j.title}\n販路：${names[j.platform]}\n状況：${labels[r.status]}\n指定価格：${money(j.price)}\nShops商品：https://jp.mercari.com/shops/product/${encodeURIComponent(j.productId)}`;}
function view(r){if(r.spec.kind==='sale'&&r.status==='pending')return 'candidates';const why=C.blocked(r.spec,stock(),Date.now(),state,legacyPending());return ['done','unchanged'].includes(r.status)?'done':r.status!=='pending'?'hold':why?'wait':'today';}
function setStatus(r,status){save(C.transition(state,r.id,status,stock(),Date.now(),legacyPending()));message=status==='done'?'記録しました。販売サイトの変更結果を記録する機能です。':'状態を保存しました';render();}
function render(){if(!panel)return;panel.replaceChildren();const h=el('header',undefined,panel);el('h2',window.DAILY_WORK_PREVIEW?'動作見本｜架空の商品・販売操作なし':'商品管理｜毎日の作業',h);button('閉じる',()=>panel.remove(),h);const top=el('div',undefined,panel,'daily-top');
 el('p','① CSVの更新状況 → ② 終了処理 → ③ 指定された作業。セール対象を探す必要はありません。',top);
 el('p','Shopsはオーナーが担当。記号は指示がある場合のみ変更します。セール準備から終了処理完了まで、その販路の自動値下げを休止してください。',top,'muted');
 el('p','取込済み商品：'+stock().length+'件 ／ '+(localStorage.getItem('csv_filename')||'ファイル名の記録なし')+' ／ '+(localStorage.getItem('csv_updated_at')||'取込日時の記録なし')+'（CSV作成日時ではありません）',top,'muted');
 const tools=el('div',undefined,top,'actions');button('CSVの確認・取り込み',()=>csvOptions(),tools);button('指定されたセール候補',()=>{tab='candidates';selected=null;render();},tools);button('本日の報告をコピー',()=>{const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});return copy(state.jobs.filter(r=>r.updatedAt&&new Date(r.updatedAt).toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'})===today).map(report).join('\n\n')||'本日の記録はありません');},tools);
 el('p','共有接続は未設定です。現在の指示と結果はこのブラウザのみ。別の端末への自動配信・同時作業の排他制御は未稼働です。',top,'notice');
 const backup=el('details',undefined,top);el('summary','予備の保存・復旧（通常の作業手順ではありません）',backup);button('控えを保存',()=>download('作業控え_'+new Date().toISOString().slice(0,10)+'.json',{format:'daily-staff-results-v1',exportedAt:new Date().toISOString(),jobs:state.jobs,saleRounds:state.saleRounds||{},salePauses:state.salePauses||{}}),backup);button('既存指示・控えを復旧',()=>importFile.click(),backup);
 const round=P.round(state,Date.now()),active=P.activeSales(state).length,legacyRows=legacyPending();el('p',`セール同時進行 ${active+legacyRows.length}/5 ／ 今週の開始 ${P.startedIds(state,Date.now()).length}/5 ／ 指定候補 ${round?.ids.length||0}/10`,top);if(P.overdue(state,Date.now(),legacyRows))el('p','終了処理が未完了です。新しいセールは開始できません。',top,'notice');
 const emergency=el('details',undefined,top);el('summary','緊急用｜手動で見つけた商品を登録',emergency);el('p','通常の日課ではありません。この販路のいいね3以上、既に指示された価格・期間がある商品に限ります。追加の記号変更・値下げは自動で行いません。',emergency);button('緊急登録フォームを開く',()=>emergencyForm(),emergency);
 if(message||loadError)el('p',loadError?'保存データを読めません。操作せずオーナーへ連絡してください。':message,top,'notice');
 const nav=el('nav',undefined,panel);for(const [v,t]of [['today','今日の作業'],['candidates','指定セール候補'],['wait','開始・予約待ち'],['hold','報告・保留'],['done','完了・訂正']]){const b=button(t+' '+state.jobs.filter(r=>visibleIn(r,v)).length,()=>{tab=v;selected=null;render();},nav);if(v===tab)b.className='active';}
 const layout=el('div',undefined,panel,'daily-layout'),list=el('aside',undefined,layout),detail=el('section',undefined,layout);
 const visible=state.jobs.filter(r=>visibleIn(r,tab)).sort((a,b)=>(a.spec.kind==='restore'?-1:0)-(b.spec.kind==='restore'?-1:0));
 for(const r of visible)button((r.spec.kind==='restore'?'終了処理｜':'')+r.spec.code+' · '+names[r.spec.platform]+' · '+money(r.spec.price),()=>{selected=r.id;render();},list);
 const r=visible.find(x=>x.id===selected)||visible[0];if(!r){el('h3','この一覧の作業はありません',detail);el('p','承認済みの指示が届くと表示します。候補が0件でも対象探しは不要です。未入力の価格や不明な条件からセールを作りません。',detail);el('p','空き時間は依頼済みの新規出品・下書きを進めます。メルカリ新規出品は1日3件まで。',detail);}else{const j=r.spec;el('h3',j.code+'｜'+names[j.platform],detail);el('p',j.title,detail);el('p',(j.kind==='restore'?'戻す価格：':'指定価格：')+money(j.price),detail,'price');const why=C.blocked(j,stock(),Date.now(),state,legacyPending())||(j.kind==='sale'?P.gate(state,j.id,stock(),Date.now(),legacyPending()):'');if(why)el('p',why,detail,'notice');
 if(j.kind==='sale'){el('p','終了：'+new Date(j.endAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})+' ／ 終了後の指定価格：'+money(j.normalPrice)+(j.endSymbol?' ／ 終了後の記号：'+j.endSymbol:''),detail);saleCheck(r,detail);}if(j.symbol)el('p','今回の記号変更：'+j.symbol+'（管理番号そのものは変更しません）',detail);
 const direct=window.StaffProductLinks?.safeUrl(j.platform,j.url);if(direct)link('商品を開く ↗',direct,detail);else el('p','一致確認済みの直接リンクなし。下の検索を使ってください。',detail);
 const search={mercari:'https://jp.mercari.com/search?keyword=',rakuma:'https://fril.jp/s?query=',yahoo_flea:'https://paypayfleamarket.yahoo.co.jp/search/'};
 const fallback=el('details',undefined,detail);el('summary','見つからない場合：従来の検索',fallback);link('管理番号で検索 ↗',search[j.platform]+encodeURIComponent(j.code),fallback);button('管理番号をコピー',()=>copy(j.code),fallback);link('Shops参考ページ ↗','https://jp.mercari.com/shops/product/'+encodeURIComponent(j.productId),fallback);
 const actions=el('div',undefined,detail,'actions');const pc=button('価格をコピー',()=>copy(String(j.price)),actions);pc.disabled=!!why||r.status!=='pending';
 if(j.kind==='sale'&&j.platform!=='yahoo_flea'){const end=new Date(j.endAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'});const comment=`【期間限定セール】\n${end}まで${money(j.price)}にお値下げしています。`; const cb=button('セールコメントをコピー',()=>copy(comment),actions);cb.disabled=!!why||r.status!=='pending';}
 el('p',j.kind==='restore'?(j.platform==='yahoo_flea'?'売れ残った商品を指定の終了後価格へ変更する。説明文の追記・削除は不要。':'売れ残った商品を指定の終了後価格へ変更し、セールコメントを削除。'):j.kind==='sale'?(j.platform==='yahoo_flea'?'価格変更だけ。商品説明へのセール文は不要。':'指定価格に変更し、セールコメントを投稿。'):('採用済みの価格に変更。'+(j.symbol?'指定の記号も変更します。':'記号変更の指示はありません。')),detail);
 const finish=button(j.kind==='restore'?'価格戻し・必要なコメント削除を完了':'変更作業を完了',()=>setStatus(r,'done'),actions);finish.disabled=!!why||r.status!=='pending';
 if(j.kind==='price'&&r.status==='pending'&&!why)button('すでに指定価格どおり（変更なし）',()=>setStatus(r,'unchanged'),detail);
 const exceptions=el('details',undefined,detail);el('summary','商品が違う・売却済み・作業できない',exceptions);for(const v of ['missing','sold','on_sale','mismatch','lower','hold'])button(labels[v],()=>setStatus(r,v),exceptions);button('報告文をコピー（Shopsリンク付き）',()=>copy(report(r)),detail);if(r.status!=='pending'&&!(j.kind==='sale'&&state.jobs.some(x=>x.id===r.id+':restore')))button('記録を取り消して選び直す',()=>setStatus(r,'pending'),detail);el('p','取り消しは作業記録だけです。販売先の価格は自動で戻りません。',detail,'muted');}
 const legacy=el('details',undefined,panel);el('summary','旧セールの終了作業・過去の記録',legacy);let count=0;const all=typeof smGetAll==='function'?smGetAll():{};for(const [code,sd]of Object.entries(all))for(const t of sd.tasks||[])if(t.type==='revert_check'&&t.status==='pending'){count++;button(code+' 終了処理 '+(t.dueDate||''),()=>smOpenRevertChecklist(code,t.id),legacy);}for(const [code,sd]of Object.entries(all))if(sd.trial20261004&&!sd.trial20261004.legacyReleased)button(code+' 販売試験の終了・取消',()=>openSalesTrial(code),legacy);
 el('p',count?'旧セールの未処理分を残しています。':'旧セールの終了待ちはありません。',legacy);link('旧A・Bの記録を見る（新規配布なし）','emergency.html',legacy);
}
const importFile=document.createElement('input');importFile.type='file';importFile.accept='.json';importFile.onchange=async()=>{try{const file=importFile.files[0];if(!file)return;const data=JSON.parse(await file.text());const next=data.format==='daily-staff-results-v1'?C.restore(state,data):C.merge(state,data);save(P.prepare(next));message='取り込みました。既存の完了記録は保持しています。';render();}catch(e){message=e.message;render();}finally{importFile.value='';}};
function csvOptions(){render();const area=el('section',undefined,panel,'sale-form');area.scrollIntoView();el('h3','CSVの更新状況を確認',area);el('p','このツールへ最新CSVを取り込んだ直後なら、再取り込みは不要です。Driveへのアップロードだけでは、このブラウザの商品データは更新されません。',area);
 const use=button('取り込み済みのデータで作業へ',()=>{message='取り込み済みデータを使用します。自動で再取得はしません。';render();},area);use.disabled=!stock().length;
 button('パソコンのCSVファイルから取り込む',()=>{panel.remove();openCsvModal();},area);
 button('Driveから再取得する',async()=>{message='Driveから取得中です…';render();const result=await smLoadCsvFromDrive();message=result?.ok?'CSVを'+result.count+'件取り込みました。':(result?.message||'Drive連携先から取得できませんでした。取り込み済みデータか、CSVファイル取り込みを使用してください。');render();},area);
 el('p','CSVファイルを選択 → 表示された内容を確認 →「インポート実行」。終了後に「商品管理を開く」へ戻ってください。通信失敗時は既存データを削除しません。',area);}
function emergencyForm(){render();const form=el('section',undefined,panel,'sale-form');form.scrollIntoView();el('h3','緊急用｜手動で見つけた商品の登録',form);el('p','いいね3以上。承認済みのセール価格と期間を入力します。記号変更や追加の値引きはここでは設定しません。開始・終了処理の上限と休止確認は通常と共通です。',form);
 const inputs={};function input(k,label,type){const line=el('label',label,form),i=el('input',undefined,line);i.type=type;inputs[k]=i;return i;}
 input('code','管理番号（原文のまま）','text');const platform=el('select',undefined,form);for(const p of C.platforms){const o=el('option',names[p],platform);o.value=p;}platform.value='mercari';input('url','一致を確認した商品URL','url');input('normal','現在価格・終了後に戻す価格','number');input('price','オーナー指示のセール価格','number');input('likes','この販路のいいね数（3以上）','number');input('start','開始日時（日本時間）','datetime-local');input('end','終了日時（日本時間）','datetime-local');
 button('緊急候補として記録',()=>{const code=inputs.code.value,matches=stock().filter(i=>i.code===code);if(matches.length!==1||!matches[0].shopItemId)throw Error('管理番号・商品を一意に照合できません');const likes=Number(inputs.likes.value);if(!Number.isSafeInteger(likes)||likes<3)throw Error('この販路のいいね3以上が対象です');const item=matches[0],start=inputs.start.value+':00+09:00',end=inputs.end.value+':00+09:00';const j={id:'emergency:'+item.shopItemId+':'+platform.value+':'+start,code,productId:item.shopItemId,title:item.title,platform:platform.value,kind:'sale',source:'emergency',url:inputs.url.value,normalPrice:Number(inputs.normal.value),price:Number(inputs.price.value),startAt:start,endAt:end};const next=P.nominateEmergency(C.merge(state,{format:'daily-staff-v1',batch:'emergency',jobs:[j]}),j.id);save(P.screen(next,j.id,{currentPrice:j.normalPrice,likes}));tab='candidates';selected=j.id;message='緊急候補を保存しました。実際の販売価格は変更していません。';render();},form);}
function legacyPending(){const rows=[];const all=typeof smGetAll==='function'?smGetAll():{};const day=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});for(const [code,sd]of Object.entries(all))for(const t of sd.tasks||[])if(t.type==='revert_check'&&t.status==='pending')rows.push({code,overdue:!t.dueDate||t.dueDate<=day});for(const [code,sd]of Object.entries(all))if(sd.trial20261004&&!sd.trial20261004.legacyReleased)rows.push({code,overdue:true});return rows;}
function visibleIn(r,v){if(v==='candidates')return r.status==='pending'&&r.spec.kind==='sale'&&!!P.round(state,Date.now())?.ids.includes(r.id);return view(r)===v;}
function saleCheck(r,parent){if(r.status!=='pending')return;const b=P.round(state,Date.now()),previous=b?.checks[r.id];const box=el('div',undefined,parent,'sale-check');el('p','価格の再審査ではありません。不定期値下げによる実価格のずれだけ確認します。合わなければ見送り、代わりの商品探しは不要です。',box);const label=el('label','この販路の現在価格',box),actual=el('input',undefined,label);actual.type='number';actual.value=previous?.currentPrice||'';const ll=el('label',(r.spec.platform==='yahoo_flea'||r.spec.source==='emergency')?'この販路のいいね数（3以上が条件）':'いいね数（任意・不明なら空欄）',box),likes=el('input',undefined,ll);likes.type='number';likes.value=previous?.likes??'';button('実価格を記録して作業条件を確認',()=>{save(P.screen(state,r.id,{currentPrice:Number(actual.value),likes:likes.value===''?null:Number(likes.value)}));message='確認を記録しました。条件に合わない場合は変更しないでください。';render();},box);}
// Owner-side integration entry points. No public feed, discounts or private data are inferred.
window.DailyWork={receiveApprovedInstructions(pack){save(P.prepare(C.merge(state,pack)));render();return {jobs:state.jobs.length};},confirmAutoDiscountPause(platform,until){save(P.pause(state,platform,until));render();},snapshot(){return JSON.parse(JSON.stringify(state));}};
window.openDailyWork=function(){if(!loadError)save(P.prepare(state));if(!panel)panel=el('div',undefined,undefined);panel.id='daily-work';document.body.appendChild(panel);render();};window.openSaleModal=window.openDailyWork;
setInterval(()=>{if(panel?.isConnected&&!panel.querySelector('.sale-form')&&!panel.querySelector('input:focus')){if(!loadError)save(P.prepare(state));render();}},60000);
const style=el('style',undefined,document.head);style.textContent='#daily-work{position:fixed;inset:0;z-index:10010;background:#101722;color:#eef2f7;overflow:auto;padding:24px;font:15px system-ui}#daily-work header,#daily-work nav,#daily-work .actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}#daily-work h2{flex:1}#daily-work button,#daily-work input,#daily-work select{padding:10px 14px;border:1px solid #52627a;border-radius:8px;background:#243348;color:#fff;margin:4px 0}#daily-work button{cursor:pointer}#daily-work button:disabled{opacity:.4;cursor:default}#daily-work .active{background:#276c83}#daily-work .daily-layout{display:grid;grid-template-columns:300px 1fr;gap:24px;margin:20px 0}#daily-work aside button{display:block;width:100%;text-align:left}#daily-work section,#daily-work .daily-top{padding:20px;background:#182333;border-radius:12px}#daily-work a{color:#8fd7ff;display:inline-block;margin:8px}#daily-work .price{font-size:28px;font-weight:bold}#daily-work .notice{color:#ffd18a}#daily-work .muted{color:#b5c1d3;font-size:13px}#daily-work label{display:block}#daily-work label input{margin-left:12px}@media(max-width:720px){#daily-work .daily-layout{grid-template-columns:1fr}}';
})();
