(function(){'use strict';
const C=window.DailyWorkCore,KEY='daily_staff_work_v1',names={mercari:'メルカリ',rakuma:'ラクマ',yahoo_flea:'Yahoo!フリマ'},labels={pending:'未着手',done:'完了',unchanged:'指定価格どおり（変更なし）',missing:'見つからない',sold:'この販路で売却済み',on_sale:'別のセール中',mismatch:'商品違い',lower:'指定より安い',hold:'オーナーへ相談'};
let panel,selected,tab='today',message='',loadError=false;
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{"jobs":[]}');if(!Array.isArray(x.jobs))throw Error();return x;}catch(e){loadError=true;return {jobs:[]};}}
let state=read();
function save(next){if(loadError)throw Error('作業データを読めません。上書きせずオーナーへ連絡してください');localStorage.setItem(KEY,JSON.stringify(next));state=next;}
function el(tag,text,parent,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;if(parent)parent.appendChild(n);return n;}
function button(text,fn,parent){const b=el('button',text,parent);b.onclick=async()=>{try{await fn();}catch(e){message=e.message;render();}};return b;}
function link(text,url,parent){const a=el('a',text,parent);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function money(n){return Number(n).toLocaleString()+'円';}
function stock(){return window.items||[];}
function copy(t){return navigator.clipboard.writeText(t).then(()=>{message='コピーしました';render();});}
function download(name,obj){const u=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function report(r){const j=r.spec;return `管理番号：${j.code}\n商品名：${j.title}\n販路：${names[j.platform]}\n状況：${labels[r.status]}\n指定価格：${money(j.price)}\nShops商品：https://jp.mercari.com/shops/product/${encodeURIComponent(j.productId)}`;}
function view(r){const why=C.blocked(r.spec,stock());return ['done','unchanged'].includes(r.status)?'done':r.status!=='pending'?'hold':why?'wait':'today';}
function setStatus(r,status){save(C.transition(state,r.id,status,stock()));message=status==='done'?'記録しました。販売サイトの変更結果を記録する機能です。':'状態を保存しました';render();}
function render(){if(!panel)return;panel.replaceChildren();const h=el('header',undefined,panel);el('h2','商品管理｜毎日の作業',h);button('閉じる',()=>panel.remove(),h);const top=el('div',undefined,panel,'daily-top');
 el('p','① 最新CSVを取り込む → ② 今日の作業 → ③ 終了処理 → ④ 報告・保存。価格の再承認は不要です。',top);
 el('p','Shopsはオーナーが担当。記号の定期変更・旧400件の一括消化は行いません。自動値下げツールと同時に価格変更しないでください。',top,'muted');
 const tools=el('div',undefined,top,'actions');button('最新CSVを取り込む',()=>{panel.remove();smLoadCsvFromDrive();},tools);button('指示・保存結果を取り込む',()=>importFile.click(),tools);button('セール対象を準備',()=>saleForm(),tools);button('本日の報告をコピー',()=>{const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});return copy(state.jobs.filter(r=>r.updatedAt&&new Date(r.updatedAt).toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'})===today).map(report).join('\n\n')||'本日の記録はありません');},tools);button('作業結果を保存',()=>download('作業結果_'+new Date().toISOString().slice(0,10)+'.json',{format:'daily-staff-results-v1',exportedAt:new Date().toISOString(),jobs:state.jobs}),tools);
 el('p','作業記録はこのブラウザに保存。1日の最後に「作業結果を保存」でオーナーへ渡してください。A・B別の配布はありません。',top,'muted');
 if(message||loadError)el('p',loadError?'保存データを読めません。操作せずオーナーへ連絡してください。':message,top,'notice');
 const nav=el('nav',undefined,panel);for(const [v,t]of [['today','今日の作業'],['wait','開始・予約待ち'],['hold','報告・保留'],['done','完了・訂正']]){const b=button(t+' '+state.jobs.filter(r=>view(r)===v).length,()=>{tab=v;selected=null;render();},nav);if(v===tab)b.className='active';}
 const layout=el('div',undefined,panel,'daily-layout'),list=el('aside',undefined,layout),detail=el('section',undefined,layout);
 const visible=state.jobs.filter(r=>view(r)===tab).sort((a,b)=>(a.spec.kind==='restore'?-1:0)-(b.spec.kind==='restore'?-1:0));
 for(const r of visible)button((r.spec.kind==='restore'?'終了処理｜':'')+r.spec.code+' · '+names[r.spec.platform]+' · '+money(r.spec.price),()=>{selected=r.id;render();},list);
 const r=visible.find(x=>x.id===selected)||visible[0];if(!r){el('h3','この一覧の作業はありません',detail);el('p','3販路セールは「セール対象を準備」から登録できます。指示がない商品を日数だけで値下げ・再出品しないでください。',detail);el('p','空き時間は依頼済みの新規出品・下書きを進めます。メルカリ新規出品は1日3件まで。',detail);}else{const j=r.spec;el('h3',j.code+'｜'+names[j.platform],detail);el('p',j.title,detail);el('p',(j.kind==='restore'?'戻す価格：':'指定価格：')+money(j.price),detail,'price');const why=C.blocked(j,stock());if(why)el('p',why,detail,'notice');
 const direct=window.StaffProductLinks?.safeUrl(j.platform,j.url);if(direct)link('商品を開く ↗',direct,detail);else el('p','一致確認済みの直接リンクなし。下の検索を使ってください。',detail);
 const search={mercari:'https://jp.mercari.com/search?keyword=',rakuma:'https://fril.jp/s?query=',yahoo_flea:'https://paypayfleamarket.yahoo.co.jp/search/'};
 const fallback=el('details',undefined,detail);el('summary','見つからない場合：従来の検索',fallback);link('管理番号で検索 ↗',search[j.platform]+encodeURIComponent(j.code),fallback);button('管理番号をコピー',()=>copy(j.code),fallback);link('Shops参考ページ ↗','https://jp.mercari.com/shops/product/'+encodeURIComponent(j.productId),fallback);
 const actions=el('div',undefined,detail,'actions');const pc=button('価格をコピー',()=>copy(String(j.price)),actions);pc.disabled=!!why||r.status!=='pending';
 if(j.kind==='sale'&&j.platform!=='yahoo_flea'){const end=new Date(j.endAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'});const comment=`【期間限定セール】\n${end}まで${money(j.price)}にお値下げしています。期間終了後は通常価格に戻します。`;const cb=button('セールコメントをコピー',()=>copy(comment),actions);cb.disabled=!!why||r.status!=='pending';}
 el('p',j.kind==='restore'?(j.platform==='yahoo_flea'?'売れ残った商品を元の価格へ戻す。説明文の追記・削除は不要。':'売れ残った商品を元の価格へ戻し、セールコメントを削除。'):j.kind==='sale'?(j.platform==='yahoo_flea'?'価格変更だけ。商品説明へのセール文は不要。':'指定価格に変更し、セールコメントを投稿。'):'採用済みの価格に変更。記号は変更しません。',detail);
 const finish=button(j.kind==='restore'?'価格戻し・必要なコメント削除を完了':'変更作業を完了',()=>setStatus(r,'done'),actions);finish.disabled=!!why||r.status!=='pending';
 if(j.kind==='price'&&r.status==='pending'&&!why)button('すでに指定価格どおり（変更なし）',()=>setStatus(r,'unchanged'),detail);
 const exceptions=el('details',undefined,detail);el('summary','商品が違う・売却済み・作業できない',exceptions);for(const v of ['missing','sold','on_sale','mismatch','lower','hold'])button(labels[v],()=>setStatus(r,v),exceptions);button('報告文をコピー（Shopsリンク付き）',()=>copy(report(r)),detail);if(r.status!=='pending')button('記録を取り消して選び直す',()=>setStatus(r,'pending'),detail);el('p','取り消しは作業記録だけです。販売先の価格は自動で戻りません。',detail,'muted');}
 const legacy=el('details',undefined,panel);el('summary','旧セールの終了作業・過去の記録',legacy);let count=0;const all=typeof smGetAll==='function'?smGetAll():{};for(const [code,sd]of Object.entries(all))for(const t of sd.tasks||[])if(t.type==='revert_check'&&t.status==='pending'){count++;button(code+' 終了処理 '+(t.dueDate||''),()=>smOpenRevertChecklist(code,t.id),legacy);}for(const [code,sd]of Object.entries(all))if(sd.trial20261004&&!sd.trial20261004.legacyReleased)button(code+' 販売試験の終了・取消',()=>openSalesTrial(code),legacy);
 el('p',count?'旧セールの未処理分を残しています。':'旧セールの終了待ちはありません。',legacy);link('旧A・Bの記録を見る（新規配布なし）','emergency.html',legacy);
}
const importFile=document.createElement('input');importFile.type='file';importFile.accept='.json';importFile.onchange=async()=>{try{const file=importFile.files[0];if(!file)return;const data=JSON.parse(await file.text());const next=data.format==='daily-staff-results-v1'?C.restore(state,data):C.merge(state,data);save(next);message='取り込みました。既存の完了記録は保持しています。';render();}catch(e){message=e.message;render();}finally{importFile.value='';}};
function saleForm(){render();const form=el('section',undefined,panel,'sale-form');form.scrollIntoView();el('h3','セール準備｜メルカリ・ラクマ・Yahoo!フリマ',form);el('p','元の価格は販路ごとに保存します。オーナーから指示されたセール価格・期間を使用。Yahoo!フリマはいいね3件以上を対象に選んでください。Shopsのいいね数は代用しません。',form);
 const fields={};function input(k,label,type,value){const l=el('label',label,form),i=el('input',undefined,l);i.type=type;i.value=value||'';fields[k]=i;return i;}
 input('code','管理番号','text');const ps=el('select',undefined,form);for(const p of C.platforms){const o=el('option',names[p],ps);o.value=p;}
 input('url','商品URL（任意）','url');input('normal','この販路の現在価格','number');input('sale','指示されたセール価格','number');input('start','開始日時（日本時間）','datetime-local');input('end','終了日時（日本時間）','datetime-local');
 const config=window.OPERATIONS_CONFIG||{highPrice:30000};el('p','オーナー指示が未確定の価格・時間は推測せず、対象選びまで進めてください。',form);
 button('この販路をセール予定に追加',()=>{const code=fields.code.value.trim(),matches=stock().filter(i=>i.code===code);if(matches.length!==1||!matches[0].shopItemId)throw Error('管理番号を一意に照合できません');const item=matches[0],normal=Number(fields.normal.value),amount=normal-Number(fields.sale.value);if(!C.price(normal))throw Error('現在価格を入力してください');const start=fields.start.value+':00+09:00',end=fields.end.value+':00+09:00';if(Date.parse(end)<=Date.now())throw Error('終了日時が過ぎています');const platform=ps.value,url=fields.url.value.trim();if(url&&!window.StaffProductLinks.safeUrl(platform,url))throw Error('この販路の商品URLを入力してください');const id='sale:'+code+':'+platform+':'+start;if(state.jobs.some(r=>r.spec.code===code&&r.spec.platform===platform&&r.spec.kind==='sale'&&r.status!=='sold'&&Date.parse(r.spec.endAt)>Date.parse(start)&&Date.parse(r.spec.startAt)<Date.parse(end)))throw Error('同じ期間のセールが登録済みです');const job={id,code,productId:item.shopItemId,title:item.title,platform,kind:'sale',normalPrice:normal,price:normal-amount,startAt:start,endAt:end,...(url?{url}:{}),...(normal>=config.highPrice?{holdReason:'高額商品のセール：オーナーの個別指示待ち'}:{})};save(C.merge(state,{format:'daily-staff-v1',batch:'sale-plan',createdAt:new Date().toISOString(),jobs:[job]}));message='予定を保存しました。販売サイトはまだ変更されていません。';tab='wait';render();},form);
}
window.openDailyWork=function(){if(!panel)panel=el('div',undefined,undefined);panel.id='daily-work';document.body.appendChild(panel);render();};window.openSaleModal=window.openDailyWork;
setInterval(()=>{if(panel?.isConnected&&!panel.querySelector('.sale-form'))render();},60000);
const style=el('style',undefined,document.head);style.textContent='#daily-work{position:fixed;inset:0;z-index:10010;background:#101722;color:#eef2f7;overflow:auto;padding:24px;font:15px system-ui}#daily-work header,#daily-work nav,#daily-work .actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}#daily-work h2{flex:1}#daily-work button,#daily-work input,#daily-work select{padding:10px 14px;border:1px solid #52627a;border-radius:8px;background:#243348;color:#fff;margin:4px 0}#daily-work button{cursor:pointer}#daily-work button:disabled{opacity:.4;cursor:default}#daily-work .active{background:#276c83}#daily-work .daily-layout{display:grid;grid-template-columns:300px 1fr;gap:24px;margin:20px 0}#daily-work aside button{display:block;width:100%;text-align:left}#daily-work section,#daily-work .daily-top{padding:20px;background:#182333;border-radius:12px}#daily-work a{color:#8fd7ff;display:inline-block;margin:8px}#daily-work .price{font-size:28px;font-weight:bold}#daily-work .notice{color:#ffd18a}#daily-work .muted{color:#b5c1d3;font-size:13px}#daily-work label{display:block}#daily-work label input{margin-left:12px}@media(max-width:720px){#daily-work .daily-layout{grid-template-columns:1fr}}';
})();
