const test=require('node:test'),assert=require('node:assert/strict'),C=require('./daily_work_core'),P=require('./daily_sale_plan');
const now=Date.parse('2026-10-01T21:00:00+09:00');
const job=(n,more={})=>({id:'s'+n,code:'TEST_'+n,productId:'id'+n,title:'合成テスト',url:'https://jp.mercari.com/item/m'+n,platform:'mercari',kind:'sale',normalPrice:10000,price:9000,startAt:'2026-10-01T20:00:00+09:00',endAt:'2026-10-02T21:00:00+09:00',...more});
const pack=jobs=>({format:'daily-staff-v1',batch:'synthetic',jobs});
const inventory=jobs=>jobs.map(j=>({code:j.code,shopItemId:j.productId,stock:1}));
function seed(jobs){let s=P.prepare(C.merge({jobs:[]},pack(jobs)),now);return P.pause(s,'mercari','2026-10-05T23:00:00+09:00',now);}
function ready(s,id,amount=10000){return P.screen(s,id,{currentPrice:amount,likes:null},now);}
test('通常価格承認20件からセールを生成しない',()=>{const s=seed(Array.from({length:20},(_,n)=>job(n,{kind:'price'})));assert.equal(P.round(s,now),undefined);assert.equal(s.jobs.length,20);});
test('候補は最大10で固定し、例外発生・追加入稿で補充しない',()=>{let s=seed(Array.from({length:15},(_,n)=>job(n)));assert.equal(P.round(s,now).ids.length,10);const before=P.round(s,now).ids.slice();s=C.transition(s,before[0],'missing',[],now);s=C.merge(s,pack([job(20)]));assert.deepEqual(P.round(P.prepare(s,now),now).ids,before);assert.match(P.gate(s,'s20',[],now),/候補外/);});
test('候補選定は商品単位で1販路・完全な直接リンクが必要',()=>{const s=seed([job(1),job(1,{id:'rakuma',platform:'rakuma',url:'https://item.fril.jp/aabbccddeeff00112233445566778899'}),job(2,{url:'https://jp.mercari.com/search?keyword=x'}),job(3,{holdReason:'未承認'})]);assert.equal(P.round(s,now).ids.length,1);});
test('同時進行5件の上限、週を跨いでも終了前に枠が空かない',()=>{const jobs=Array.from({length:6},(_,n)=>job(n));let s=seed(jobs);for(let n=0;n<5;n++){s=ready(s,'s'+n);s=C.transition(s,'s'+n,'done',inventory(jobs),now);}s=ready(s,'s5');assert.match(P.gate(s,'s5',inventory(jobs),now),/上限/);assert.equal(P.activeSales(s).length,5);assert.equal(P.activeSales(P.prepare(s,now+7*86400000)).length,5);});
test('終了済みでも同一週の開始枠は復活しない・旧保存にも履歴から上限',()=>{let s=seed(Array.from({length:6},(_,n)=>job(n)));for(let n=0;n<5;n++){s=ready(s,'s'+n);s=C.transition(s,'s'+n,'done',inventory(s.jobs.map(r=>r.spec)),now);s=C.transition(s,'s'+n,'sold',[],now);}s=ready(s,'s5');s.saleRounds[P.weekKey(now)].started=[];assert.match(P.gate(s,'s5',[],now),/今週/);});
test('旧セールの期限超過と終了処理保留は新規を止める',()=>{let s=ready(seed([job(1),job(2)]),'s1');assert.match(P.gate(s,'s1',[],now,[{overdue:true}]),/終了処理/);s=C.transition(s,'s1','done',inventory([job(1)]),now);s=C.transition(s,'s1:restore','hold',[],now);assert.equal(P.overdue(s,now+2*86400000),1);assert.equal(P.activeSales(s).length,1);});
test('実価格の差・同額以下・古い観測・休止期限不足を開始できない',()=>{let s=seed([job(1)]);for(const amount of [8900,9000,9800,10100])assert.ok(P.gate(ready(s,'s1',amount),'s1',[],now));s=ready(s,'s1');assert.equal(P.gate(s,'s1',[],now),'');assert.match(P.gate(s,'s1',[],now+31*60000),/30分/);delete s.salePauses;assert.match(P.gate(s,'s1',[],now),/休止/);});
test('Yahoo!フリマいいね条件は他販路に流用しない',()=>{const j=job(1,{platform:'yahoo_flea',url:'https://paypayfleamarket.yahoo.co.jp/item/z1234'});let s=seed([j]);s=P.pause(s,'yahoo_flea',j.endAt,now);for(const likes of [null,0,2])assert.match(P.gate(P.screen(s,j.id,{currentPrice:10000,likes},now),j.id,[],now),/いいね/);assert.equal(P.gate(P.screen(s,j.id,{currentPrice:10000,likes:3},now),j.id,[],now),'');});
test('開始済みの訂正で終了処理を消さず、指定の記号だけを終了指示へ渡す',()=>{const j=job(1,{endSymbol:'△'});let s=C.transition(ready(seed([j]),j.id),j.id,'done',inventory([j]),now);assert.equal(s.jobs[1].spec.symbol,'△');assert.throws(()=>C.transition(s,j.id,'pending',inventory([j]),now));s=C.transition(s,j.id,'hold',[],now);assert.equal(P.activeSales(s).length,1);});
test('別販路の売却報告があれば、CSVに在庫があっても開始・価格変更しない',()=>{const jobs=[job(1,{id:'sold',platform:'rakuma',kind:'price'}),job(1)];let s=ready(seed(jobs),'s1');s=C.transition(s,'sold','sold',[],now);assert.throws(()=>C.transition(s,'s1','done',inventory([job(1)]),now),/売却報告/);});
test('控え復旧で候補・開始枠が保持され、異なる記録は上書きしない',()=>{let s=ready(seed([job(1)]),'s1');s=C.transition(s,'s1','done',inventory([job(1)]),now);const file={format:'daily-staff-results-v1',exportedAt:new Date(now).toISOString(),...s};assert.deepEqual(C.restore({jobs:[]},file),s);assert.throws(()=>C.restore(s,{...file,saleRounds:{[P.weekKey(now)]:{...P.round(s,now),started:[]}}}));assert.throws(()=>C.restore({jobs:[]},{...file,salePauses:{mercari:{at:'x',until:'x'}}}));});
test('JST月曜で週を切り替え、空の受信ではその週を消費しない',()=>{assert.equal(P.weekKey(Date.parse('2026-10-04T23:59:59+09:00')),'2026-09-28');assert.equal(P.weekKey(Date.parse('2026-10-05T00:00:00+09:00')),'2026-10-05');let s=P.prepare({jobs:[]},now);s=C.merge(s,pack([job(1)]));assert.equal(P.round(P.prepare(s,now),now).ids.length,1);});
test('期限前でも同じ商品の旧セールが残れば開始を止める',()=>{const s=ready(seed([job(1)]),'s1');assert.match(P.gate(s,'s1',[],now,[{code:'TEST_1',overdue:false}]),/旧セール/);});
test('セール中の通常価格指示は新旧どちらのセールでも止める',()=>{let s=ready(seed([job(1)]),'s1');s=C.transition(s,'s1','done',inventory([job(1)]),now);const regular=job(1,{id:'regular',kind:'price',price:9500});s=C.merge(s,pack([regular]));assert.throws(()=>C.transition(s,'regular','done',inventory([regular]),now),/セール/);const old=C.merge({jobs:[]},pack([regular]));assert.throws(()=>C.transition(old,'regular','done',inventory([regular]),now,[{code:'TEST_1',overdue:false}]),/旧セール/);});
test('売却時は保留中の終了作業も日時付きで停止',()=>{let s=C.transition(ready(seed([job(1)]),'s1'),'s1','done',inventory([job(1)]),now);s=C.transition(s,'s1:restore','hold',[],now);s=C.transition(s,'s1','sold',[],now+60000);const r=s.jobs.find(x=>x.id==='s1:restore');assert.equal(r.status,'sold');assert.equal(r.updatedAt,new Date(now+60000).toISOString());});
test('配布上限と累積履歴を区別して1001件の控えを復元',()=>{const jobs=Array.from({length:1001},(_,n)=>job(n,{kind:'price'}));assert.throws(()=>C.validate(pack(jobs)));const records=jobs.map(spec=>({id:spec.id,spec,status:'pending',history:[]}));assert.equal(C.restore({jobs:[]},{format:'daily-staff-results-v1',jobs:records}).jobs.length,1001);});
test('緊急手動候補も全販路いいね3以上・上限共通・記号は自動生成しない',()=>{const j=job(1,{source:'emergency'});let s=P.nominateEmergency(C.merge({jobs:[]},pack([j])),j.id,now);s=P.pause(s,'mercari',j.endAt,now);assert.match(P.gate(P.screen(s,j.id,{currentPrice:10000,likes:2},now),j.id,[],now),/いいね/);s=P.screen(s,j.id,{currentPrice:10000,likes:3},now);assert.equal(P.gate(s,j.id,[],now),'');const result=C.transition(s,j.id,'done',inventory([j]),now);assert.equal(result.jobs[1].spec.symbol,undefined);const full=seed(Array.from({length:10},(_,n)=>job(n)));const extra=job(100,{source:'emergency'});assert.throws(()=>P.nominateEmergency(C.merge(full,pack([extra])),extra.id,now),/上限10件/);});
